### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by jamiedee** [sxwid/admidio3.1_scoutversion#3]
Noch offen:
- [x]  Startseite verfassen
- [x]  Porträt verfassen

Generelle Überarbeitung:
- [x]  Check ob Mitglieder, Profile und Adressformulare und Seiten fehlerfrei sind
- [x] Rechte Testen Downloads (AL, Leitende, öffentlich)
- [x] Rollenverteilung überdenken
- [x]  Testing generell

Migirieren
- [x] Fotos neu hochladen (skalierung)
- [x] Fotos Geo hochladen
- [x] Umzug Mitgliederdaten
- [x] Füllen mit aktuellen Terminen
- [x] Umzug Downloads
- [x] Wechsel auf PHP7.0
- [ ] Down-/ Upgrade Hosting-Abo

**Comment by jamiedee** [comment]
Folgende Fotoalben von 2014 fehlen noch:
(und halt 2015 und 16 hab ich nicht mehr fotografieren dürfen für die PTA :(

![bildschirmfoto 2016-04-07 um 13 44 33](https://cloud.githubusercontent.com/assets/2400979/14348766/50bc4b42-fcc7-11e5-8c6e-aef8c561efb8.png)
